apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: _PROJECT_NAME_-creds
spec:
  backendType: secretsManager
  dataFrom:
  # get aws key and secret from upstream.
  - move-infra/kubernetes/prod/_PROJECT_NAME_
