[unix_http_server]
file=/tmp/supervisor.sock
username = dummy
password = dummy

[inet_http_server]
port=127.0.0.1:9009
username = dummy
password = dummy


[supervisorctl]
serverurl=unix:///tmp/supervisor.sock
serverurl=http://127.0.0.1:9009
username = dummy
password = dummy

[supervisord]
logfile=/dev/fd/1
logfile_maxbytes=0
# logfile_backups=10
loglevel=info
pidfile=/tmp/supervisord.pid
nodaemon=true
silent=false
minfds=1024
minprocs=200

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:api]
command=newrelic-admin run-program gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 api:app --reload
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0

[program:newrelic-infra]
command=/usr/bin/newrelic-infra -config /etc/newrelic-infra.yml
directory=/
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0