apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: _PROJECT_NAME_-creds
  labels:
    app: _PROJECT_NAME_
spec:
  backendType: secretsManager
  dataFrom:
  # get aws key and secret from upstream.
  - kubernetes/stage/_PROJECT_NAME_
