apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: _PROJECT_NAME_-service-monitor
  labels:
    release: prometheus
    app: _PROJECT_NAME_
spec:
  selector:
    matchLabels:
      app: _PROJECT_NAME_
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      path: /metrics
      interval: 30s